version: "3"
services:
  postgres:
    network_mode: host
    image: library/postgres:latest
    container_name: jandexGoodsDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: jandexGoodsDB
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

volumes:
  db-data: